### PR TITLE
finish my task cases01

### PR DESCRIPTION
**Pull request by asglazunova**
code here

### CODE REVIEW

**Review by Bradcolbert33 — APPROVED** [review]
This is some cool code, lets merge it

**Review by maximvoronov757 — APPROVED** [review]
Your code Anna is amazing!!!! Nice job!

**Comment by maximvoronov757** [comment]
I can watch this code whole night

**Comment by asglazunova** [comment]
Thank you guys

**Comment by AndrewChetvertakov** [comment]
Looks good, lol :D 👯

**Review by AndrewChetvertakov — APPROVED** [review]
Pew Pew.

**Pull request merged**
